name: Quality Check

on:
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/quality-check.yml'
    types:
      - opened
      - synchronize
  workflow_dispatch:

env:
  NODE_VERSION: 22.11.0
  PNPM_VERSION: 9.13.2

jobs:
  type-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js and install dependencies
        uses: ./.github/actions/install
        with:
          pnpm-version: ${{ env.PNPM_VERSION }}
          node-version: ${{ env.NODE_VERSION }}
          working-directory: frontend

      - name: Run TypeScript type check
        run: pnpm ci:typecheck

  test:
    runs-on: ubuntu-latest
    needs: type-check
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js and install dependencies
        uses: ./.github/actions/install
        with:
          pnpm-version: ${{ env.PNPM_VERSION }}
          node-version: ${{ env.NODE_VERSION }}
          working-directory: frontend

      - name: Run Vitest and coverage
        run: pnpm ci:test
        env:
          CI: true

  eslint:
    runs-on: ubuntu-latest
    needs: type-check
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js and install dependencies
        uses: ./.github/actions/install
        with:
          pnpm-version: ${{ env.PNPM_VERSION }}
          node-version: ${{ env.NODE_VERSION }}
          working-directory: frontend

      - name: Run ESLint
        run: pnpm ci:lint

  prettier:
    runs-on: ubuntu-latest
    needs: type-check
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js and install dependencies
        uses: ./.github/actions/install
        with:
          pnpm-version: ${{ env.PNPM_VERSION }}
          node-version: ${{ env.NODE_VERSION }}
          working-directory: frontend

      - name: Run Prettier
        run: pnpm ci:format

  build:
    runs-on: ubuntu-latest
    needs: [type-check, test, eslint, prettier]
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js and install dependencies
        uses: ./.github/actions/install
        with:
          pnpm-version: ${{ env.PNPM_VERSION }}
          node-version: ${{ env.NODE_VERSION }}
          working-directory: frontend

      - name: Run Build
        run: pnpm build
